---
- hosts: vyos
  gather_facts: no
  tasks:
    - name: check pwd
      vyos_command:
        commands: 
          - pwd
    - name: fetch boot files
      fetch:
        src: test
        dest: ./
        flat: yes
