---
- hosts: vyos
  gather_facts: false

  tasks:
    - name: show version
      vyos_command:
        commands:
          - show version
      register: result_version

    - name: save to file
      copy:
        content: "{{ result_version.stdout[0] }}"
        dest: "show_version.log"
